main:
	mcs StructureEditor.cs StructureEditor.Designer.cs LipidStructure.cs -r:System.dll -r:System.Windows.Forms.dll -r:System.Drawing.dll -r:System.Xml.dll -r:System.Xml.Linq.dll -sdk:4.8

release:
	dotnet build -c Release
