env:
  global:
      - BASE_BUILD_NUMBER=749
language: csharp
solution: LipidCreator.sln
mono:
 - 6.12.0
before_install:
 - export BUILD_NUMBER=$(($BASE_BUILD_NUMBER + $TRAVIS_BUILD_NUMBER))
script:
 - msbuild LipidCreator.sln /p:Configuration=Release /p:Platform=x64 /p:BuildNumber=${BUILD_NUMBER}
 - cd LipidCreator && make tests && make runtest
