CC = x86_64-w64-mingw32-g++

main:
	dmcs -r:SkylineTool.dll -lib:/usr/lib/mono/2.0 -pkg:dotnet Program.cs CreatorGUI.cs CreatorGUI.Designer.cs MS2Form.cs MS2Form.Designer.cs LipidsReview.cs LipidsReview.Designer.cs NewFragment.cs NewFragment.Designer.cs -out:LipidCreator.exe